### ISSUE TITLE
CPLD Replacement

### ISSUE THREAD

**Issue by TheDrifter363** [borti4938/n64rgb_pcb#1]
Hey Borti,

I was interested in using your mod for my n64, but it looks like the altera and amd CPLDs you recommended are no longer in stock, they're obsolete. You think your firmware could work on any alternatives? Digikey recommended me this one by Microchip:

https://www.digikey.com/en/products/detail/microchip-technology/ATF1504ASV-15AU44/1008326

I'm not sure if your firmware is manufacturer specific though. Thought I'd ask. Thanks man.

**Comment by borti4938** [comment]
The CPLD you picked is way to small to fit all functions. Actually the controller reading does not fit. If you want to go with just the basics (like on the [n64rgb_flex project](https://github.com/borti4938/n64rgb_flex), the CPLD is large enough, but I have bad experience with it; a long time ago I tried to get it to work reliably.

- My recommendation for this project: go with the MaxV CPLD setup. It is overall the cheaper option over the MaxII setup.
- For the [n64rgb_flex project](https://github.com/borti4938/n64rgb_flex) project: source CPLDs from chinese market or adapt everything to use a MaxV CPLD, e.g. using the 5M80ZE64C5N.

(I included some words on the n64rgb_flex project as I think you may mean this one. (manufacturer of CPLDs, CPLD size))

**Comment by TheDrifter363** [comment]
> The CPLD you picked is way to small to fit all functions. Actually the controller reading does not fit. If you want to go with just the basics (like on the [n64rgb_flex project](https://github.com/borti4938/n64rgb_flex), the CPLD is large enough, but I have bad experience with it; a long time ago I tried to get it to work reliably.
> 
>     * My recommendation for this project: go with the MaxV CPLD setup. It is overall the cheaper option over the MaxII setup.
> 
>     * For the [n64rgb_flex project](https://github.com/borti4938/n64rgb_flex) project: source CPLDs from chinese market or adapt everything to use a MaxV CPLD, e.g. using the 5M80ZE64C5N.
> 
> 
> (I included some words on the n64rgb_flex project as I think you may mean this one. (manufacturer of CPLDs, CPLD size))

Hey Borti thanks for responding!

Yeah I realized after I made this, I meant to post this issue on the flex page. Which I realize this isn't an issue at all, as I found a 44 pin TQFP that was compatible with your firmware.

Alright, so what I'm getting from your reply is to not use the flex pcb? Just stick with this standard n64rgb? I'm not looking for any HDMI or anything like that, just simple rgb, so this is why I was gravitating towards these pcbs.

What do you recommend, regular or flex?

**Comment by borti4938** [comment]
Personally I only use the flex version if I build some. So I guess I recommend that one over this project.

For my next order (which is not planned yet), I will probably update the CPLD there.
